In [26]:
import tensorflow as tf
from tensorflow.keras.datasets import cifar10
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from keras.utils import to_categorical
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [27]:
pickle_in = open("x_asl1.pickle","rb")
X = pickle.load(pickle_in)

pickle_in = open("y_asl1.pickle","rb")
y = pickle.load(pickle_in)

print(X.shape, X.dtype)
print(y.shape, y.dtype)

(400, 100, 100, 3) uint8
(400,) int32


In [28]:
y.shape

(400,)

In [29]:
#One-Hot Encoding
y = to_categorical(y)

#Print the new label
print(y[0])

[0. 0. 0. 0. 0. 1. 0.]


In [5]:
X, X_test, y, y_test = train_test_split( X, y, test_size=0.3, random_state=4)

In [6]:
X_test.shape

(4605, 60, 60, 3)

In [7]:
y.shape

(10742, 5)

In [202]:
model = Sequential()
model.add(Conv2D(64, kernel_size=3, activation='relu', input_shape=(60,60,1)))
model.add(Conv2D(32, kernel_size=3, activation='relu'))

model.add(Flatten())
model.add(Dense(64,activation='relu'))
model.add(Dense(5, activation='softmax'))

#Compile the model 
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=10,validation_split=0.3)

Train on 6125 samples, validate on 2625 samples
Epoch 1/10
6125/6125 [==============================] - 65s 11ms/sample - loss: 5.2418 - accuracy: 0.9512 - val_loss: 0.0072 - val_accuracy: 0.9973
Epoch 2/10
6125/6125 [==============================] - 59s 10ms/sample - loss: 0.0061 - accuracy: 0.9979 - val_loss: 0.0158 - val_accuracy: 0.9981
Epoch 3/10
2112/6125 [=========>....................] - ETA: 33s - loss: 4.1472e-04 - accuracy: 0.9995

KeyboardInterrupt: 

In [203]:
X = X/255.0

model = Sequential()

model.add(Conv2D(256, (3, 3), input_shape=X.shape[1:]))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(256, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors

model.add(Dense(64))

model.add(Dense(5))
model.add(Activation('sigmoid'))

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=20,validation_split=0.3)

Train on 6125 samples, validate on 2625 samples
Epoch 1/20
6125/6125 [==============================] - 173s 28ms/sample - loss: 0.1027 - accuracy: 0.9610


KeyboardInterrupt: 

In [33]:
model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(100,100,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3), input_shape=(100,100,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), input_shape=(100,100,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3), input_shape=(100,100,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dense(32))
model.add(Activation('relu'))
model.add(Dropout(0.5))

model.add(Dense(7))
model.add(Activation('sigmoid'))

model.summary()

model.compile(loss='categorical_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])

model.fit(X, y, batch_size=32, epochs=15,validation_split=0.3)

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_28 (Conv2D)           (None, 98, 98, 32)        896       
_________________________________________________________________
activation_49 (Activation)   (None, 98, 98, 32)        0         
_________________________________________________________________
max_pooling2d_28 (MaxPooling (None, 49, 49, 32)        0         
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 47, 47, 32)        9248      
_________________________________________________________________
activation_50 (Activation)   (None, 47, 47, 32)        0         
_________________________________________________________________
max_pooling2d_29 (MaxPooling (None, 23, 23, 32)        0         
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 21, 21, 64)       

In [34]:
model.save('asl_trained2.model')

INFO:tensorflow:Assets written to: asl_trained2.model\assets


In [11]:
Y_test_pred1 = model.predict(X_test)


In [12]:
Y_test_pred1

array([[5.7434861e-04, 1.3185437e-02, 8.6342961e-02, 3.3214107e-01,
        1.4281464e-03],
       [1.1834506e-37, 1.0000000e+00, 8.0350070e-32, 0.0000000e+00,
        2.2574095e-35],
       [9.9896598e-01, 4.6789588e-15, 1.2014853e-13, 5.7487230e-11,
        1.9950226e-10],
       ...,
       [0.0000000e+00, 1.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [5.2417858e-37, 1.0000000e+00, 3.7646106e-32, 0.0000000e+00,
        8.2930386e-32],
       [1.7124253e-22, 2.2454834e-17, 1.0000000e+00, 2.1355329e-06,
        1.2908464e-16]], dtype=float32)

In [34]:
Y_test_pred2 = []
for i in range(len(Y_test_pred1)):
    flag = False
    for j in range(5):
        if Y_test_pred1[i][j] == 1:
            Y_test_pred2.append(j)
            flag = True
    if flag != True:
        Y_test_pred2.append(0)

In [35]:
Y_test_pred2 = np.array(Y_test_pred2)
Y_test_pred2

array([3, 2, 0, ..., 0, 4, 0])

In [13]:
Y_test_pred1.shape

(4605, 5)

In [14]:
y_test.shape

(4605, 5)

In [15]:
y_test

array([[0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [16]:
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import multilabel_confusion_matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

cm = confusion_matrix(y_test, Y_test_pred1)
cm

ValueError: Classification metrics can't handle a mix of multilabel-indicator and continuous-multioutput targets

In [122]:
import seaborn as sn

CATEGORIES = ["E","F","Y","M","D"]

confusion_matrix = pd.crosstab(y_test,Y_test_pred2, rownames=['Actual'], colnames=['Predicted'])

sn.heatmap(confusion_matrix, annot=True)

print(classification_report(y_test, Y_test_pred2, target_names=CATEGORIES))


Exception: Data must be 1-dimensional

In [123]:
CATEGORIES = ["E","F","Y","M","D"]

conf_mat_dict={}

for label_col in range(len(CATEGORIES)-1):
    y_true_label = y_test[:, label_col]
    y_pred_label = Y_test_pred1[:, label_col]
    conf_mat_dict[labels[label_col]] = confusion_matrix(y_pred=y_pred_label, y_true=y_true_label)


for label, matrix in conf_mat_dict.items():
    print("Confusion matrix for label {}:".format(label))
    print(matrix)

ValueError: Classification metrics can't handle a mix of binary and continuous targets

In [110]:
Y_test_pred2.shape

(2625,)

In [111]:
y_test.shape

(106, 5)